spring.application.name=Todo-App-HW
server.error.include-stacktrace=ALWAYS
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:postgresql://localhost:5432/items
spring.datasource.username=postgres
spring.datasource.password=1234
spring.jpa.show-sql=true
app.profile.name=Dev